# The name of the deployment
name: Career Canvas Manual Deployment

# When this action will be executed
on: workflow_dispatch

jobs:
  # Job run image.
  build:
    runs-on: ubuntu-latest

    # Steps that need to happen in this job run.
    steps:
      # Check out the code
      - name: Check out code
        uses: actions/checkout@v2

      # Login to Docker Hub
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      # Build the Docker image
      - name: Build Docker image
        run: docker build -t charanposthog:latest .

      # tag the Docker image
      - name: Tag Docker image
        run: docker tag charanposthog:latest ${{ secrets.DOCKER_USERNAME }}/charanposthog:${{ github.sha }}

        # Push the Docker image
      - name: Push Docker image
        run: docker push ${{ secrets.DOCKER_USERNAME }}/charanposthog:${{ github.sha }}

      - name: Login to Azure
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Deploy to Azure Container Apps
        run: |
          az containerapp update \
            --name charanzencon \
            --resource-group ZenPOC \
            --image ${{ secrets.DOCKER_USERNAME }}/charanposthog:${{ github.sha }}
