# The name of the deployment
name: posthog-container app Manual Deployment

# When this action will be executed
on: workflow_dispatch

jobs:
  # Job run image.
  build:
    runs-on: ubuntu-latest

    # Steps that need to happen in this job run.
    steps:
      # Check out the code
      - name: Check out code
        uses: actions/checkout@v2

      # Login to Docker Hub
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password:
            ${{ secrets.DOCKER_PASSWORD }}

            # Build the Docker image
      - name: Build Docker image
        run: |
          docker build \
            --build-arg KINDE_CLIENT_ID="57ca032eb46d4594a0fc6b3f0e7a9304" \
            --build-arg KINDE_CLIENT_SECRET="clw0pkuWTb6b7GmIiGbO3lOtBdHWWNIHi238MNSAVGfNdhUPWMi" \
            --build-arg NEXT_PUBLIC_APP_URL="https://charanzencon.ashymeadow-dd775b15.centralindia.azurecontainerapps.io" \
            -t charanposthog:latest .

      # tag the Docker image
      - name: Tag Docker image
        run: docker tag charanposthog:latest ${{ secrets.DOCKER_USERNAME }}/charanposthog:${{ github.sha }}

        # Push the Docker image
      - name: Push Docker image
        run: docker push ${{ secrets.DOCKER_USERNAME }}/charanposthog:${{ github.sha }}

        # Log in to Azure
      # - name: Log in to Azure
      #   uses: azure/login@v1
      #   with:
      #     # use Azure credentials for the login
      #     creds: ${{ secrets.AZURE_CREDENTIALS }}
      # # Deploy to Azure Container Apps
      # - name: Deploy to Azure Container Apps
      #   uses: azure/container-apps-deploy-action@v0
      #   with:
      #     containerAppName: ${{ vars.CONTAINER_APP_NAME }}
      #     imageToDeploy: docker.io/${{ secrets.DOCKER_USERNAME  }}/charanposthog:${{ github.sha }}
